#!/bin/bash

touch /home/user/nick-email.db
chown user /home/user/nick-email.db
grep -E '^M[UN]' /path/to/atheme/etc/services.db | awk '{print $1" "$2" "$3" garble " $5" "$6" "$7" "$8" "$9}' > /home/user/nick-email.db
